### ISSUE TITLE
pnpm install error from https://github.com/cpreston321/nuxt-swiper/tree/feat/elements

### ISSUE THREAD

**Issue by wangzhaohe** [cpreston321/nuxt-swiper#112]
nuxt 3.8

```
~/learning/nuxt/nuxt-swiper/examples/swiper-basic main                                                                                                      rb 2.7.2
> pnpm install
Scope: all 2 workspace projects
../..                                    |    +1133 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
../..                                    | Progress: resolved 1133, reused 1126, downloaded 0, added 1133, done
../.. prepare$ nuxt-module-build prepare && nuxi prepare .playground
│ ℹ Compiled plugins/server.mjs in 578.39ms
│ ℹ Compiled plugins/client.mjs in 614.28ms
│ ✔ Types generated in .nuxt
│  ERROR  Cannot find module '/Users/swot/learning/nuxt/nuxt-swiper/dist/module.cjs'. Please verify that the package.json has a valid "main" entry
│   at tryPackage (node:internal/modules/cjs/loader:436:19)
│   at Module._findPath (node:internal/modules/cjs/loader:678:18)
│   at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
│   at Function.resolve (node:internal/modules/cjs/helpers:116:19)
│   at _resolve (node_modules/.pnpm/jiti@1.20.0/node_modules/jiti/dist/jiti.js:1:250334)
│   at jiti (node_modules/.pnpm/jiti@1.20.0/node_modules/jiti/dist/jiti.js:1:252917)
│   at .playground/nuxt.config.ts:2:32
│   at evalModule (node_modules/.pnpm/jiti@1.20.0/node_modules/jiti/dist/jiti.js:1:255614)
│   at Object.jiti (node_modules/.pnpm/jiti@1.20.0/node_modules/jiti/dist/jiti.js:1:253542)
│   at resolveConfig (node_modules/.pnpm/c12@1.5.1/node_modules/c12/dist/index.mjs:288:24)
│  ERROR  Cannot find module '/Users/swot/learning/nuxt/nuxt-swiper/dist/module.cjs'. Please verify that the package.json has a valid "main" entry
└─ Failed in 5.7s at /Users/swot/learning/nuxt/nuxt-swiper
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by wangzhaohe** [comment]
1. first `npm run build` in nuxt-swiper directory, The /dist/module.cjs will be created first.
2. then `npm run dev`
